name: hequest
description: Simple and hackable request for dart. Built on top of the http package.
version: 0.0.3
homepage: https://github.com/teixeirazeus/hequest
repository: https://github.com/teixeirazeus/hequest

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http: ^0.13.5